buildbot/master.cfg
We require Android 4.3 minimum now, which is API level 18.
=> Update Android Native API level to 18.

central/buildbot.py
No idea what it means but GitHub sometimes delivers events with mergeable_state="unknown" and mergeable=None. Checking explicitly for False should fix the randomly occurring problem that central marks a PR as unmergeable even though GitHub says it is mergeable.
=> central: build PRs even if mergeable=None

central/buildbot.py, central/config.yml
To avoid unimportant GitHub notifications, add an IRC command `irrawaddy rebuild pr 1234` similar to the GitHub command `@dolphin-emu-bot rebuild`. Requires op ~~or voice~~ as authentication.
Suggested by @mathieui. Untested.
=> central: add rebuild command for IRC

buildbot/master.cfg
Currently some test files get included in the `.dmg` package generated for OS X nightly builds. This commit ensures that only app bundles will be included in the packaged dmg file.
This reduces the size of nightly `Dolphin.dmg` files from 6.4 Mo to 4.7 Mo,
by excluding the `Tests` directory and the `traversal_server` binary.
Fixes [issue 8084](https://dolp.in/i8084). @parlane I saw you are the owner of this issue, maybe you want to have a look?
=> Exclude Test files from nightly OS X package

buildbot/master.cfg
PRs are built as 'debug', so they have a different filename as a result. This should correct for that.
=> Point Android PR uploads at the correct filename.

central/ircclient.py
I’m not totally sure replace is the best thing to use here, if we are 100% sure the URL will always have that form we could use a substring instead.
=> irrawaddy: replace goo.gl with dolp.in in issues

buildbot/master.cfg
They use ninja to build parallel internally, so there is no need to run
two build scripts at once.
=> Limit all unix slaves to max_builds=1

central/config.yml, central/events.py, central/ircclient.py, central/redmine.py
(This doesn't work for imported issues, but we're mostly getting new issues now anyways.)
=> central: add update number to shortened issue URLs

buildbot/master.cfg
Android projects typically use a Gradle "wrapper" bundled with the project, which reads a file in the project, `gradle-wrapper.properties`, to determine what version of Gradle to use to build the project. This means that if a build process feature requires a new version of Gradle, all that's necessary is a change to that file, and the CI server will automatically download the appropriate requisite as part of the first build that requires it.
This change should switch to using that wrapper, instead of a manually-installed Gradle distribution. 
To be honest, I'm not sure if this change will do it - it should work as long as the current working directory is the Android project's root, but I'm not positive of that.
=> [Android] Use Gradle Wrapper bundled with project repo to build the project

buildbot/master.cfg
It's already our minimum requirement and it is needed to support the KHR_create_context extension without defining everything ourselves.
=> Increase Android native API level to 21(Android 5.0)

buildbot/master.cfg
Allows ffmpeg to properly be included in OSX builds
=> Remove -DENCODE_FRAMEDUMPS=OFF flag from OSX

central/events.py, central/github.py, central/ircclient.py
This makes the IRC bot ignore PR comment edited or deleted events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/sadm/61)
=> IRC: Ignore "comment edited/deleted" events

central/buildbot.py, central/events.py, central/github.py, central/ircclient.py
Apparently comments on pull requests are treated as issue comments, so the previous PR had no effect most of the time (even if it didn't break something…)
This is a more complete change to handle GitHub comment actions correctly:
- Rebuilds are only triggered when the comment is created. This should prevent duplicate rebuilds if someone creates the rebuild comment and then deletes it. (which I think is what is intended)
- The IRC comment messages now indicate the action correctly, instead of only showing "commented" even for deletions/edits.
(I double-checked this time and the event should be correct (verified with the recent events page), and hopefully I haven't missed anything)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Handle GitHub comment actions

buildbot/master.cfg
CMake + ninja are now called by gradle, no need to call it ourself.
This must be merged together with https://github.com/dolphin-emu/dolphin/pull/4252
=> Buildbot: Update android build to the android studio 2.2 way.

central/events.py, central/github.py, central/ircclient.py
GitHub sends a review event in addition to a review comment event when someone replies to an earlier comment or adds a single comment, even when they didn't really submit a pull request review. (This makes no sense to me, but that's how they designed their PR reviews.)
To prevent useless notifications, we skip any "review" which only has one comment, since there is already a comment notification for those.
Additionally, since we now have info on associated comments, we can show whether comments were posted for an approval review event.
=> central: Skip PR reviews which have only one review comment

central/utils.py
Gives the URL shortener a better response in the case of an empty URL.
=> central/utils: handle empty url for shortener

central/utils.py
<irrawaddy> [dolphin-emu/dolphin] J﻿osJuice commented on #3763 (Always clear memory when booting): <goo.gl invalid response>
Long link is better than no link.
edit: stupid html tags
=> Return the original URL if shortening fails

central/buildbot.py, central/ircclient.py
* Fix the commit status link for pending builds.
* Remove a useless review notification. This is now required because GH has started sending out events for pending reviews.
=> central: Minor fixes

central/buildbot.py
Buildbot defers to the explicit revisions when they're available, rather than fetching the PR ref from GitHub. This causes it to only build the base ref, rather than the actual PR.
=> central: don't send base_rev or head_rev to buildbot

buildbot/master.cfg
Instead of applying PRs as patches and leaving them as staged changes, the lint builder now checks out the PR branch, so we must run lint on all files that were touched by commits in the PR branch (not on master), not staged files.
=> buildbot: Run lint against commits that are not on master

buildbot/master.cfg
They're usually really quick and people should be informed about what they need to change asap instead of minutes later.
=> buildbot: Prioritise lint builds

buildbot/master.cfg
Makes sure the baserev exists locally, in an attempt to fix the `invalid symmetric difference expression` errors. GitHub's "baserev" property is the current base branch head, which isn't guaranteed to exist in the PR branch (e.g. if it hasn't been rebased)!
=> buildbot: fetch base rev before linting against it

redirector/main.go
An extension to the README was recently added but the file is also read from here and needs to be updated too.
Otherwise going to dolp.in will result in the message "No README found. Cannot provide you with documentation ☹".
=> Redirect lookup for the README.md file

buildbot/master.cfg
Fetching a single revision is an optional host feature, and it is disabled on github. This fails right now if the PR isn't based on master directly.
=> lint: Fetch all revisions.

buildbot/master.cfg
The Qt version of Dolphin has to be signed too.
=> Buildbot/OSX: Sign Qt app bundle

central/utils.py
Use the dolp.in redirector service instead of goo.gl for common URL patterns.
=> shorten_url: use redirector if available

buildbot/master.cfg
I find console view very useful (better than waterfall these days); any chance of adding it here?
Here's what it looks like for mGBA: https://buildbot.mgba.io/#/console
=> buildbot: enable console view

buildbot/master.cfg
Also removes ENABLE_WX=OFF, as it is no longer valid. Should fix the fifoci runners.
(fifoci has been broken for a while)
=> buildbot: replace ENABLE_QT2=OFF with ENABLE_QT=OFF

buildbot/master.cfg
Causes the bundle to explode in size.
=> buildbot/master.cfg: Disable frame dump encoding on macOS

central/ircclient.py
* Improve notification wording for PR actions. Instead of "username synchronize pull request #12345", the IRC bot will now say "username synchronized ...". Merges are now announced as merges and not as closures. etc.
* Ignore PR review edits as those notifications are useless.
=> ircclient: Small improvements for GitHub notifications

central/events.py, central/github.py
Follow-up to #101. Sorry, I forgot that evt isn't the GitHub webhook data but a GHPullRequest event, so the new properties also need to be added there.
=> central: Add missing properties to GHPullRequest event

buildbot/send_build.py
Looks like the script was still being run with Python 2, which causes
it to break if any of the environment variables contains non-ASCII
characters (like the é in my name...)
=> buildbot: Run send_build.py with Python 3

buildbot/master.cfg, central/config.yml
This PR adds a fifoci builder that uses OpenGL with Ubershaders.  I put this on arbert, which currently runs fifoci-ogl-lin-radeon, to try and balance it with hive, which runs fifoci-ogl-lin-mesa and fifoci-sw-lin-mesa.  This is under the assumption that the software renderer takes about as long as ubershaders, but I don't know for sure if that's actually the case (and my machine is too weak to make good comparisons).
Requires dolphin-emu/fifoci#36.  I haven't tested this myself, as I don't have anything set up locally.
Note that I've also sync'd central's config.yml with what I think should be correct.  Delroth mentioned that it didn't match what was currently in use in production (which makes sense given the API keys are dummied out), and that's consistent with pr-fifoci-ogl-lin-nv …
=> Add uberogl fifoci builders

buildbot/master.cfg
This is the corresponding change to the buildbots for:
https://github.com/dolphin-emu/dolphin/pull/9441
In theory this should be all the changes needed to support adding the M1 buildbot-worker when we have the machine, however I was only able to test part of it locally as I was unable to reproduce all of Dolphin's build infrastructure (like code signing, and the github integration).
=> Apple M1: Add M1 buildbot-worker

buildbot/master.cfg
Overrides the x64 macOS deployment target to 10.12 in the legacy Intel only
buildbot. The universal buildbot already targets 10.12 in the build script.
=> Override CMake Deployment Target for macOS x64

buildbot/master.cfg
This is the sadm change corresponding to: https://github.com/dolphin-emu/dolphin/pull/9830
It just adds the command line flag to execute the unit tests to the build command. It should be merged after https://github.com/dolphin-emu/dolphin/pull/9830 as it will cause the universal build to fail without the corresponding updates to the build script.
=> M1: Add flag to run unit tests during universal builds

buildbot/make_manifest.py
[Writing the update manifest for the macOS universal version of 5.0-14753 failed](https://dolphin.ci/#/builders/27/builds/235) because a directory on the content store was non-existent when line 17 was executed, but was apparently created by something else (another buildbot?) before line 18 was executed. 
`os.makedirs` throwing a `FileExistsError` shouldn't be a problem, so ignore it.
=> make_manifest: Allow content store directory to already exist when attempting to create it

buildbot/master.cfg
The wip builders were removed by https://github.com/dolphin-emu/sadm/commit/336d0e6064679019cfb5720d83b8008e2e0983c9, so these lines do nothing.
=> buildbot: remove remnants of wip builders

buildbot/master.cfg
Make the macOS and universal macOS builders use different output file
names for the repacked DMG -- otherwise they can race with each other
and overwrite another builder's DMG. That would cause a manifest
to be generated for the wrong build...
This issue was hit with Dolphin 35bf5e38392670b3b86a4926437d01157363ba4a
=> buildbot: fix a race condition between macos and macos-universal builders

central/buildbot.py
This was removed when I added support for Buildbot pending build events
as I had assumed that Buildbot would send build events fast enough.
However one problem that is made obvious by the occasional build upload
issues is that Buildbot only sends events when a build has started
and not when a build is queued, which means that a builder getting
stuck can cause PRs to get the green "all checks passed" status
even when builds haven't actually started on some builders.
=> central: Send PR status events before triggering builds

buildbot/master.cfg
Companion PR to dolphin-emu/dolphin#10037.
The Intel builder sets the `CMAKE_OSX_DEPLOYMENT_TARGET` to 10.12 Sierra, so we need to update it here too.
=> buildbot: Set minimum macOS to 10.13 High Sierra on Intel builder

buildbot/master.cfg
As initially planned when the decision to add a universal builder
was made earlier this year.
=> buildbot: remove old macOS (Intel) builder

central/utils.py
goo.gl has been dead for a while so all the removed code did was spam
the log with "[ERROR] URL shortening failed because of a network error"
=> central: remove goo.gl URL shortening code

buildbot/master.cfg
I tried to bisect an issue recently and ended up with many "Dolphin" disks on my Desktop. I couldn't tell which disk contained which version.
This PR makes it so that the name of the volume contains the version number in normal builds ("Dolphin 5.0-12345") or the PR number for PR builds ("Dolphin pr-12345").
=> buildbot: Add shortrev or branchname to DMG volume name

buildbot/master.cfg
Based on how Linux FifoCI is triggered.
All the necessary setup has been completed on the build machine. I have also completed a local test run by executing ``runner.py`` manually, and it generated the ``result.zip`` file without issue.
=> buildbot: Add support for macOS FifoCI

buildbot/master.cfg
This PR codesigns the Dolphin and Dolphin Updater applications with our new Developer ID certificate, and then notarizes the disk image. The scripts, build keychain, and certificates have already been set up on the machine.
In terms of notarization, all development, beta, and stable builds are submitted to the Apple notary service. PR builds are not notarized. (Apple says that we should limit requests to the notary service to 75 per day, so I chose to not include PR builds given that PRs can be rebuilt several times.)
When a build is submitted to the notary service, ``notarytool`` waits for it to return a result. When it does, we staple the result to the binaries afterwards using ``stapler``. (Apple states that most software takes less than 5 minutes to notarize, and 98% of software …
=> buildbot: Codesign macOS binaries with Developer ID certificate and notarize

central/ircclient.py
Users often forget that they need to be opped to use commands, since irrawaddy gives the same output in either case.
Currently the only commands that exist check if the user is opped:
https://github.com/dolphin-emu/sadm/blob/f6053a71ba792bfeb324abadac505d7db0f58561/central/buildbot.py#L158-L175
https://github.com/dolphin-emu/sadm/blob/38433caf317fafb66c46efdbf6bed03fbf9d21c0/central/admin.py#L11-L18
It might be better to give more detailed information in the commands themselves, but this is still a helpful clue.
This PR is completely untested, but note that [per a doc comment in the Pypeul source](https://pypi.org/project/Pypeul/#files) `BoldRed` and `BoldLtGreen` are legal:
<details>
```python
class Tags:
'''
This class is used to represent mIRC-style formatted text
Here are a few …
```
=> ircclient: Wark in red instead of green if the user is not trusted

buildbot/master.cfg
This reverts commit 1c7f931fca917f7cbaf81d860ea2b7b6363e26f1.
I think we should probably add a Metal runner too so we can test that backend, but let's see if this works first.
=> Revert "buildbot: temporarily disable macOS FifoCI until the random diffs are fixed

buildbot/master.cfg
Continuation of #165 
This is likely the best way of implementing the generation step given that there isn't a reasonable way of running a gradle task from another module with additional arguments. This becomes worse if we try to start another gradle instance from the app module where issues like java home directories and cross platform building become more of an issue.
=> buildbot: Automatically generate baseline profiles

buildbot/master.cfg, buildbot/steampipe_app_build.vdf, buildbot/upload_to_steampipe.sh
Supersedes #166.
This PR adds builders for Steam builds (release and PR). Release builders will automatically upload their artifacts to SteamPipe and set them as live on a beta branch. PR builders will upload their artifacts to `dl.dolphin-emu.org` as normal.
Here's how the release builder works:
* The `release-steam` builder gets run along with the usual release builders.
* This builder then starts the `release-steam-all` triggerable, which in turn starts the `release-steam-*`builders and waits for them to finish.
* The final builds are uploaded to the buildbot master at `/tmp/steam/<commit hash>/win.7z`, `mac.dmg`, and `lin.7z`.
* `release-steam` extracts all the builds to a `content` subdirectory.
* SteamCMD is then used to upload the builds to SteamPipe using the …
=> buildbot: Add support for creating Steam builds and uploading them to SteamPipe

containers/ubuntu-lts-builder/Dockerfile
NDK was out of date and caused problems on first run
=> android buildbot: Update ndk to 25.1.8937393

buildbot/master.cfg
Since the android builder keeps giving us problems when compiling the android gui, I'm starting to suspect that the workaround for gradle is causing problems. To help alleviate this I'm gonna try deleting all the build files for the app module so we avoid issues between PRs.
=> buildbot: Clean android app build files before each build

buildbot/master.cfg
While the Steam runtime doesn't ship with libevdev, it *does* ship with a copy of SDL2. We need to enable our SDL input backend so that controllers actually work.
Forgot to enable this in the last PR.
=> buildbot: Enable SDL on Steam runtime builds

buildbot/master.cfg
Continuation of #165
Additionally, KVM will need to be enabled on the android container before this is merged.
=> android buildbot: Generate baseline profiles on release build

buildbot/master.cfg
In the event re-running with RunUnitTests=true actually causes compilation, limit the targets to only UnitTests project and dependencies.
=> msbuild UnitTests: only build UnitTests

buildbot/master.cfg
This *should* generate and upload android app bundles to the website.
Just some rationale around app bundles
- Reduced download size
- Debug symbols are shipped to the play console so we can actually read the crash logs
=> android-buildbot: Generate Android App Bundles

buildbot/master.cfg
This also resolves the issue where macOS universal builds did not have their distributor set.
=> buildbot: Set distributor to Steam on Steam builds

containers/debian-builder/Dockerfile, containers/ubuntu-lts-builder/Dockerfile
tested locally on ubuntu 22.04.2
note qt6-base-private-dev is only required for `<qpa/qplatformnativeinterface.h>` so maybe we should rethink if that is really needed: https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/DolphinQt/MainWindow.cpp#L33
=> ubuntu/debian: qt5 -> qt6

containers/ubuntu-lts-builder/Dockerfile
Android builds will fail when we update to AGP 8.0 which requires Java 17
=> ubuntu-lts-builder: Install Java 17 for Android

roles/android-updater/updater.py
We don't want to silently ignore errors other than the error 400 that the previous commit added handling for.
=> android-updater: Rethrow HttpError when not handled
