dolphin-emu/sadm

buildbot/master.cfg

Add a FreeBSD buildslave. I probably won't get a chance to spin it up until tomorrow, even if this gets merged before then.
I didn't have a good way to test this, so I might have missed some stuff.

Add FreeBSD builder

---

buildbot/master.cfg

Fix FreeBSD changes

---

buildbot/master.cfg

Folks have been complaining they can't test Android changes because the PRs don't get uploaded anywhere. They were being built, but not made available.
This hopefully fixes that. I'm not a buildbot expert though, so I probably messed something up.

Upload Android APKs from Github Pull Requests.

---

buildbot/master.cfg

It's already installed on the Debian buildslave.

buildbot: use ninja on the Linux buildslaves

---

ec2/ubuntu-nv/startup.sh

Workaround until the EC2 image gets updated.

Fix Ninja build on fifoci-ogl-lin-nv

---

buildbot/master.cfg

Buildbot: Rename freebsd to freebsd-x64 for consistency

---

buildbot/master.cfg
central/buildbot.py

Hopefully fixes issues with certain PRs never building.

buildbot: Fetch PR refs directly from GitHub

---

central/buildbot.py

Change Central not to send dummy pending build events right after triggering a build, and instead get them from Buildbot along with the build URL.

central: Handle pending build events

---

buildbot/master.cfg

This moved with the switch to a new gradle version.

Fix location of APK output.

---

buildbot/repack_dmg.sh

buildbot: Add script for turning .dmg into .7z files

---

buildbot/make_manifest.py

Required before #104 can be merged.

buildbot/make_manifest.py: Add --platform parameter

---

buildbot/master.cfg

Update ``master.cfg`` to generate manifests for macOS.

buildbot/master.cfg: Implement macOS Updater support

---

buildbot/master.cfg

master.cfg: Fix some hdiutil stuff

---

buildbot/master.cfg
buildbot/repack_dmg.sh

buildbot/repack_dmg.sh: Use dmg2img

---

buildbot/repack_dmg.sh

I forgot about https://github.com/dolphin-emu/sadm/blob/master/buildbot/make_manifest.py#L56

buildbot/repack_dmg.sh: Don't strip initial directory

---

central/config.yml

We have control of the new channels now, please migrate the bot when you have time.

Migrate irrawaddy to Libera.Chat

---

buildbot/master.cfg

* remove debug-win-x64 builder
* remove signbin.bat invocation
* add release-win-arm64 builder

windows buildbot updates

---

buildbot/master.cfg

Relates to https://github.com/dolphin-emu/fifoci/pull/54

buildbot: Add support for Metal FifoCI runner

---

containers/ubuntu-lts-builder/Dockerfile

Depends on [this](https://github.com/dolphin-emu/dolphin/pull/11571)

Android builder dependency updates

---

machines/altair/default.nix
secrets/secrets.nix

MayImilae: IRC/libera on 2023-04-18 08:03:55 (+2), logged in as MayImilae
OatmealDome: https://github.com/OatmealDome/sadm/commit/1f5c20a4bc831b34c6596ef8dc1df1310e45728f fetched on 2023-04-18 08:04 (+2)
JosJuice: Discod/PM on 2023-04-18 08:56 (+2), logged in as Jos#3274
Please don't drop your own key, delroth.

Add new ssh keys to the key pass and for the root login of altair.

---

buildbot/master.cfg

To be paired with [this](https://github.com/dolphin-emu/dolphin/pull/12183) PR

android buildbot: Update baseline profile command
